<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>forward_dynamics_robot_arm</name>
  <version>0.0.0</version>
  <description>Forward-dynamics robot-arm experiments for controller and design co-optimization.</description>
  <maintainer email="divij.grover@tum.de">Divij Grover</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
</package>
<!-- Generated on Fri Feb 02 12:05:43 2024 -->
